#! /bin/bash
#
# Adapted from Tom Romo's slaunch
#

# Load modules
module load cuda/9.0 gcc
module load openmm/7.2.1

# Default variables
DRIVER=/path-to/cycler.sh
TIMELIMIT="12:00:00"
NODES="1"
PARTITION="gpu"
CPT="8"
MEM="16gb"

export PARTITION
export TIMELIMIT
export DRIVER
export MEM

# Read in command line
META=`pwd | perl -anF/ -e 'print$F[$#F-1],".",$F[$#F];' | sed 's/-/_/g'`
JOBNAME="$1-$META"

# Submit job
sbatch --partition $PARTITION --time $TIMELIMIT -c $CPT --overcommit --gres gpu:$NODES --mem $MEM --job-name $JOBNAME --error $JOBNAME.err --output $JOBNAME.out $DRIVER

